# Generated by Django 5.0.2 on 2024-03-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupdetails',
            old_name='gmail',
            new_name='email',
        ),
    ]
